version: '1'

services:
  exam-project:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: examProject.com
    image: examproject:desa
    container_name: examproject
    ports:
      - "8000:80"
    networks:
      - default
networks:
  default:
    external: false
    name: services_default